USE [master]
ALTER DATABASE [ClientDemo] SET SINGLE_USER WITH ROLLBACK IMMEDIATE
RESTORE DATABASE [ClientDemo] FROM  DISK = N'G:\UAEPPE01_ClientDemo_FULL_20230629_170027.bak' WITH  FILE = 1,  NOUNLOAD,  REPLACE,  STATS = 5
ALTER DATABASE [ClientDemo] SET MULTI_USER
