SELECT * FROM HirarchyMapping_OM

UPDATE HirarchyMapping_OM SET keyType ='FixedStrings' WHERE ID >=213

UPDATE HirarchyMapping_OM SET keyType ='SingleAlphabets' WHERE keytype IS NULL >=213

DELETE FROM HirarchyMapping_OM WHERE ID >=79 AND ID<=182

;WITH e1(n) AS
(
    SELECT 1 UNION ALL SELECT 1 UNION ALL SELECT 1 UNION ALL 
    SELECT 1 UNION ALL SELECT 1 UNION ALL SELECT 1 UNION ALL 
    SELECT 1 UNION ALL SELECT 1 UNION ALL SELECT 1 UNION ALL SELECT 1
), -- 10
e2(n) AS (SELECT 1 FROM e1 CROSS JOIN e1 AS b) -- 10*10
	
SELECT SUBSTRING(TAB.str1,TAB2.RowNum,1) AS Alphabet, TAB2.RowNum
FROM (VALUES('AS'))TAB(str1)
    CROSS APPLY(
				  SELECT TOP 100 PERCENT RowNum = ROW_NUMBER() OVER (ORDER BY n) FROM e2 
				  ORDER BY n
			)TAB2