SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/*==============================================================================================
OBJECT NAME	 :  dbo.ValidateUniverse_HeightAndDepth_NG
PURPOSE	     :  VALIDATES IF THE PARENT DEPTH IN THE UNIVERSE TABLE MATCHES WITH THE HIGHEST DEPTH OF IT'S CHIDLREN
				THE FINAL RESULTSET SHOULD NOT RETURNING ANYTHING, IF IT DOES THEN THE DEPTH OF RETURNED UNIVERSE HAVE NOT BEEN STAMPED CORRECTLY
CREATED BY	 :  
CREATION DATE:  

USAGE: EXEC dbo.ValidateUniverse_HeightAndDepth

CHANGE HISTORY:
SNo.   MODIFIED BY		DATE 			DESCRIPTION
===============================================================================================*/

CREATE OR ALTER PROCEDURE [dbo].[ValidateUniverse_HeightAndDepth]
AS
BEGIN

	IF OBJECT_ID('TEMPDB..#TMP') IS NOT NULL
		DROP TABLE #TMP

	IF OBJECT_ID('TEMPDB..#T') IS NOT NULL
		DROP TABLE #T

	SELECT UniverseID AS ID,ParentID,Height,Depth INTO #TMP FROM dbo.UNIVERSE

	DECLARE @ID INT, @UniverseID INT

	DECLARE @TBL_InValidHierarchy TABLE(UniverseID INT)
	CREATE TABLE #T(Depth INT)

	--LOOP THROUGH THE COMPLETE HIERARCHY: ASSUMPTION IS HIERARCHY IS CREATED AS PER INCREASING ORDER OF PK
	WHILE EXISTS(SELECT 1 FROM #TMP)
	BEGIN
		
			SELECT @ID = MIN(ID) FROM #TMP
			--SELECT @UniverseID = UniverseID FROM #TMP WHERE ID = @ID

			--GET ALL CHILDRENT OF A NODE
			;WITH CTE
			AS(
				SELECT ID,ParentID, Height, Depth
				FROM #TMP WHERE ID=@ID
				UNION ALL
				SELECT T.ID,T.ParentID, T.Height, T.Depth
				FROM CTE C
					 INNER JOIN #TMP T ON T.ParentID = C.ID
			)
			,CTE2 AS
			(
			SELECT *,ROW_NUMBER()OVER(ORDER BY HEIGHT) AS ROWNUM			
			FROM CTE
			)

			--CHECK IF THE DEPTH IS THE SAME AS THE HIGHEST DEPTH OF ITS CHILDREN
			INSERT INTO #T(Depth)
			SELECT Depth FROM CTE2 WHERE ROWNUM=1			
			UNION
			SELECT MAX(Depth) FROM CTE2
	
			IF (SELECT COUNT(*) FROM #T)>1
				INSERT INTO @TBL_InValidHierarchy (UniverseID) VALUES(@ID)
					
			DELETE FROM #TMP WHERE ID = @ID
			DELETE FROM #T
	END

	SELECT * FROM @TBL_InValidHierarchy

END



