
IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'userlogin' AND COLUMN_NAME ='clientID')
	ALTER TABLE userlogin ADD ClientID INT
	
	DROP TABLE IF EXISTS #TMP
	
	--SELECT * FROM sys.tables WHERE type = 'U' 
	SELECT TABLE_NAME, CONCAT('ALTER TABLE ',table_name, ' ADD ClientID AS dbo.fnGetClientID(UserCreated)') AS strSQL
		INTO #TMP FROM INFORMATION_SCHEMA.TABLES TBL
	WHERE TABLE_TYPE ='BASE TABLE'
		 AND TABLE_NAME <> 'userlogin'
		 AND EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE table_name = TBL.TABLE_NAME AND COLUMN_NAME = 'UserCreated')

		 --SELECT *  FROM #TMP
		 DECLARE @SQL VARCHAR(MAX)

			SELECT	@SQL =  STUFF
							((SELECT CONCAT('; ',strSQL)
							FROM #TMP								 
							FOR XML PATH ('')
							),1,1,'');
			
			PRINT @SQL

			SET XACT_ABORT ON
			BEGIN TRAN;
				EXEC(@SQL)
			ROLLBACK


