--CREATE TABLE DYNAMICALLY
DECLARE @TBL TABLE(COLNAME VARCHAR(100),DataType VARCHAR(100),ColumnLength VARCHAR(100))

INSERT INTO @TBL
(
    COLNAME,
	DataType,
	ColumnLength
)
VALUES('COL1','VARCHAR','100'),('COL2','INT',NULL),('COL3','DATETIME',NULL),('COL4','DATETIME',NULL),('COL5','BIGINT',NULL)

--SELECT * FROM @TBL t
--SELECT * FROM SYS.COLUMNS WHERE object_id =OBJECT_ID('t1')

DECLARE @SQL VARCHAR(MAX)
DECLARE @CreateTableSQL VARCHAR(100)='CREATE TABLE dbo.'
DECLARE @TableName VARCHAR(100)='t1'
DECLARE @CheckTableSQL VARCHAR(MAX) = CONCAT('IF NOT EXISTS(SELECT 1 FROM SYS.TABLES WHERE NAME=''',@TableName,''')')
DECLARE @DropTableSQL VARCHAR(MAX) = CONCAT('IF EXISTS(SELECT 1 FROM SYS.TABLES WHERE NAME=''',@TableName,''')',CHAR(10), 'DROP TABLE ',@TableName,';')
DECLARE @AlterTableSQL VARCHAR(MAX) = CONCAT('IF EXISTS(SELECT 1 FROM SYS.TABLES WHERE NAME=''',@TableName,''')',CHAR(10), 'ALTER TABLE ',@TableName,' ADD ')
DECLARE @StandardColList VARCHAR(MAX) = 'ID_FK BIGINT, UserCreated BIGINT, DateCreated DATETIME2(0),UserModified BIGINT, DateModified DATETIME2(0),'
DECLARE @DynamicColList VARCHAR(MAX)


IF NOT EXISTS(SELECT 1 FROM SYS.TABLES WHERE NAME=@TableName)
BEGIN

	--BUILD THE LIST OF DYNAMIC COLUMNS
	SELECT @DynamicColList = STUFF(
	(SELECT CONCAT(', ',COLNAME,' ',DataType,' ', CASE WHEN DataType ='VARCHAR' THEN CONCAT('(',ColumnLength,')')ELSE '' END)
	FROM @TBL t
	FOR XML PATH('')
	)
	,1,1,'')

	SET @SQL = CONCAT(@CheckTableSQL,CHAR(10),@CreateTableSQL,@TableName,'(',@StandardColList,@DynamicColList,')',CHAR(10))
	--SET @SQL = CONCAT(@DropTableSQL,CHAR(10),@CreateTableSQL,@TableName,'(',@StandardColList,@DynamicColList,')',CHAR(10))

	PRINT @SQL
	EXEC(@SQL)

END
ELSE	--ALTER TBALE TO ADD NEW COLUMNS
BEGIN
	
	DROP TABLE IF EXISTS #TBL_NewColumns

	SELECT COLNAME
		INTO #TBL_NewColumns
	FROM @TBL t
	EXCEPT
	SELECT NAME FROM SYS.COLUMNS WHERE object_id =OBJECT_ID(@TableName)

	IF EXISTS(SELECT 1 FROM #TBL_NewColumns)
	BEGIN
		DELETE TBL FROM @TBL TBL WHERE NOT EXISTS(SELECT 1 FROM #TBL_NewColumns WHERE ColName = TBL.COLNAME)
		SELECT * FROM @TBL

		--BUILD THE LIST OF DYNAMIC COLUMNS
		SELECT @DynamicColList = STUFF(
		(SELECT CONCAT(', ',COLNAME,' ',DataType,' ', CASE WHEN DataType ='VARCHAR' THEN CONCAT('(',ColumnLength,')')ELSE '' END)
		FROM @TBL t
		FOR XML PATH('')
		)
		,1,1,'')

		SET @SQL = CONCAT(@AlterTableSQL,@DynamicColList,CHAR(10))
		PRINT @SQL
		EXEC(@SQL)
	END

END


